name: Black Format
on: [pull_request]
jobs:
  formatCheck:
    name: Black Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Black Check
        uses: psf/black@stable
